### ISSUE TITLE
Youtube support

### ISSUE THREAD

**Issue by AlttiRi** [tophf/trust-any-html#2]
Tried to use this script (`trust-any-html`) to fix [my ujs](https://github.com/AlttiRi/href-taker) on [youtube](https://www.youtube.com/).
But with this script youtube does not work at all, the Chromium-based browser only displays `zClosurez` text on the web page.

---

```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
```
![image](https://github.com/user-attachments/assets/fcb7bd23-654a-46b6-bc23-0337c3dccbe7)

**Comment by AlttiRi** [comment]
https://greasyfork.org/en/scripts/433051-trusted-types-helper/code
from this comment
https://github.com/violentmonkey/violentmonkey/issues/1873#issuecomment-2265237105
helps.

**Comment by tophf** [comment]
That script seems like a better solution, so I don't see the point of having my script maintained.
